plugins {
    id 'net.neoforged.moddev' version '1.0.17'
    id 'idea'
}

version = "${mod_version}"
group = 'igentuman.mbtool'
base {
    archivesName = "MultiBuilderTool-${minecraft_version}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"

neoForge {
    version = project.neoforge_version

    runs {
        client {
            client()
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'
            systemProperty 'neoforge.enabledGameTestNamespaces', 'mbtool'
        }

        server {
            server()
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'
            systemProperty 'neoforge.enabledGameTestNamespaces', 'mbtool'
        }

        data {
            data()
            programArguments.addAll '--mod', 'mbtool', '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
    }

    mods {
        mbtool {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven { url "https://minecraft.curseforge.com/api/maven/" }
    maven { url "https://maven.blamejared.com" }
    maven { url "https://jitpack.io" }
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven { url "https://squiddev.cc/maven/" }
    maven { url "https://maven.tterrag.com/" }
    maven { url "https://modmaven.dev/" }
    maven { url "https://maven.firstdarkdev.xyz/snapshots/" }
    maven { url "https://maven.architectury.dev" }
    maven { url "https://maven.saps.dev/minecraft" }
    maven {
        url "https://maven.latvian.dev/releases"
        content {
            includeGroup "dev.latvian.mods"
            includeGroup "dev.latvian.apps"
        }
    }

    maven {
        url 'https://jitpack.io'
        content {
            includeGroup "com.github.rtyley"
        }
    }
}

dependencies {

    runtimeOnly "curse.maven:immersive-engineering-231951:6733669"

    runtimeOnly "curse.maven:extreme-reactors-250277:7344744"
    runtimeOnly "curse.maven:zerocore-247921:7344742"

    runtimeOnly "curse.maven:nbtedit-reborn-678133:6125444"

    compileOnly "curse.maven:gregtechceu-modern-890405:6766269"

    implementation "dev.architectury:architectury-neoforge:${architectury_version}"

    implementation "curse.maven:emi-580555:6420931"

    compileOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"
    compileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}"

    implementation "mekanism:Mekanism:${minecraft_version}-${mekanism_version}"
    implementation "mekanism:Mekanism:${minecraft_version}-${mekanism_version}:generators"

    implementation "dev.latvian.mods:kubejs-neoforge:${kubejs_version}"
    implementation "curse.maven:rhino-416294:6886923"

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.2'
    testImplementation 'org.mockito:mockito-core:5.11.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.11.0'
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "mbtool",
                "Specification-Vendor"    : "igentuman",
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : "igentuman",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                "MixinConfigs"            : "mbtool.mixins.json"
        ])
    }
}

jar.enabled = true

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

configurations {
    shaded {
        transitive = false
    }
}

test {
    useJUnitPlatform()
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            'version': version,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}
