# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
mod_version=1.1.25
ae2_version=12.9.8
cc_version=1.109.5
oc2_version=6280699
md_version=4873115
sedna_version=5261893
ct_version=10.1.39
jei_version=19.27.0.336
patchouli_version=84-FORGE
mekanism_version=10.7.18.84
top_version=1.21.1-10.0.1-3
ctm_version=1.1.6+8
kubejs_version=2101.7.2-build.336
architectury_version=13.0.8
gtm_version=1.6.4
minecraft_version=1.21.1
neoforge_version=21.1.199
mappings_version=2024.07.28
java_version=21