modLoader="javafml"
loaderVersion="[7.0,)"
license="${mod_license}"
[[mods]] 
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="logo.png"
credits=""
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.mbtool]]
modId="neoforge" 
mandatory=true 
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.mbtool]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
